server.port: 7004

spring:
  datasource:
    url: jdbc:sqlite:build/sqlite.db
    username: admin
    password: admin
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.devshred.sqlite.SQLiteDialect
