server.port: 7002

spring:
  datasource:
    url: jdbc:h2:./build/h2.db;AUTO_SERVER=true
    username: user
    password: user
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect