server.port: 7006

spring:
  datasource:
    url: jdbc:firebird:local:./build/firebase.fdb?encoding=UTF8
    username: SYSDBA
    password: masterkey
    driver-class-name: org.firebirdsql.jdbc.FBDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.FirebirdDialect